import { initAudio } from "./core/audio.js";
import { initPageTemplate } from "./rooms/page-template.js";
import { initMenu } from "./core/menu.js";
import { initMenuSound } from "./core/menu-sound.js";
import { initPresentationLock } from "./core/presentation-lock.js";
import { initRoomController } from "./core/room-controller.js";
import { initDocumentary } from "./rooms/documentary.js";
import { initFieldNotes } from "./rooms/field-notes.js";
import { initCollections } from "./rooms/collections.js";
import { initOpening } from "./rooms/founder.js";
import { initFounderHub } from "./rooms/founder-hub.js";
import { initFounderMission } from "./rooms/founder-mission.js";
import { initWaitlist } from "./services/waitlist.js";
import { initLauncher } from "./core/launcher.js";
import { initTouchFeedback } from "./core/touch-feedback.js";

initWaitlist();
initPageTemplate();
initAudio();
initMenuSound();
initMenu();
initLauncher();
initTouchFeedback();
initPresentationLock();
initRoomController();
initOpening();
initFounderHub();
initFounderMission();
initFieldNotes();
initDocumentary();
initCollections();
