import { initAudio } from "./core/audio.js";
import { initMenu } from "./core/menu.js";
import { initMenuSound } from "./core/menu-sound.js";
import { initPresentationLock } from "./core/presentation-lock.js";
import { initRoomController } from "./core/room-controller.js";
import { initDocumentary } from "./rooms/documentary.js";
import { initFieldNotes } from "./rooms/field-notes.js";
import { initOpening } from "./rooms/founder.js";
import { initFounderHub } from "./rooms/founder-hub.js";
import { initFounderMission } from "./rooms/founder-mission.js";
import { initWaitlist } from "./services/waitlist.js";

initWaitlist();
initAudio();
initMenuSound();
initMenu();
initPresentationLock();
initRoomController();
initOpening();
initFounderHub();
initFounderMission();
initFieldNotes();
initDocumentary();
